version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/TSIC-Core-Angular"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/TSIC-Core-Angular/src/frontend/tsic-app"
    schedule:
      interval: "weekly"
