services:
  api:
    build:
      context: .
      dockerfile: TSIC-Core-Angular/src/backend/TSIC.API/Dockerfile
    ports:
      - "5022:5022"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=tsic;User Id=sa;Password=Your_strong_Password1;
      - SEQ_URL=http://seq:5341
    depends_on:
      - db
      - seq

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_strong_Password1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
