// Route <-> help integrity check. The frontend owns the route table, so it's the only place that can
// statically prove every keyed route has help and every help folder is reachable from a route. Run via
// `npm run verify:help` (CI / pre-commit). Exits non-zero on drift.
//
// Rules:
//   1. Every route `helpKey: '<component>'` must have public/help/<component>/overview.html.
//   2. Every public/help/<component> folder must be referenced by some route helpKey.
//   3. Every topic file must be named overview.html, faq.html, or pro-tips.html (the tabs the launcher renders).
//   4. No content file may carry an inline style="" attribute. Presentation is class-only — the block
//      vocabulary lives in styles/_help-content.scss, so a restyle is one edit, not a sweep across pages.
//   5. The committed manifest.json and search-index.json must match the content they describe. Both
//      are generated and committed, so editing a help page without running a build leaves them
//      stale — and a stale search index fails SILENTLY: search finds text that is no longer there
//      and misses text that is, which reads as a search bug rather than a missing build step.
import { readdir, readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildHelpArtifacts, sameContent } from './help-index.mjs';

const scriptsDir = dirname(fileURLToPath(import.meta.url));
const appDir = join(scriptsDir, '..', 'src', 'app');
const helpDir = join(scriptsDir, '..', 'public', 'help');
const KNOWN_TOPICS = new Set(['overview', 'faq', 'pro-tips']);

// 1. Collect helpKeys declared in the route table(s).
const routeKeys = new Set();
const routeFiles = (await readdir(appDir, { recursive: true, withFileTypes: true }))
  .filter((e) => e.isFile() && e.name.endsWith('.routes.ts'))
  .map((e) => join(e.parentPath ?? e.path, e.name));
for (const file of routeFiles) {
  const text = await readFile(file, 'utf8');
  for (const m of text.matchAll(/helpKey:\s*['"]([^'"]+)['"]/g)) {
    routeKeys.add(m[1].split('/')[0]);
  }
}

// 2. Collect help component folders + validate topic file names.
const helpComponents = new Map(); // component -> Set(topics)
const errors = [];
for (const c of await readdir(helpDir, { withFileTypes: true })) {
  if (!c.isDirectory()) continue;
  const topics = new Set();
  for (const f of await readdir(join(helpDir, c.name))) {
    if (!f.endsWith('.html')) continue;
    const topic = f.slice(0, -'.html'.length);
    if (!KNOWN_TOPICS.has(topic)) {
      errors.push(`unexpected topic file public/help/${c.name}/${f} (only overview.html / faq.html / pro-tips.html render)`);
    }
    // Content is class-only — an inline style="" defeats the shared _help-content.scss vocabulary.
    const html = await readFile(join(helpDir, c.name, f), 'utf8');
    if (/\sstyle\s*=/.test(html)) {
      errors.push(`inline style found in public/help/${c.name}/${f} — use a help-* class from styles/_help-content.scss instead`);
    }
    topics.add(topic);
  }
  helpComponents.set(c.name, topics);
}

// 3. Cross-check.
for (const key of routeKeys) {
  if (!helpComponents.has(key)) {
    errors.push(`route helpKey '${key}' has no public/help/${key}/ folder`);
  } else if (!helpComponents.get(key).has('overview')) {
    errors.push(`route helpKey '${key}' is missing public/help/${key}/overview.html`);
  }
}
for (const component of helpComponents.keys()) {
  if (!routeKeys.has(component)) {
    errors.push(`public/help/${component}/ is orphaned — no route declares helpKey '${component}'`);
  }
}

// 4. Derived artifacts must match the content. Generated by the SAME code that writes them
//    (help-index.mjs), so this can only fail on genuine staleness, never on the checker drifting
//    from the generator. Compared line-ending agnostically: the working copy is CRLF on Windows.
const built = await buildHelpArtifacts(helpDir);
for (const [file, expected] of [
  ['manifest.json', built.manifestJson],
  ['search-index.json', built.indexJson],
]) {
  const actual = await readFile(join(helpDir, file), 'utf8').catch(() => null);
  if (actual === null) {
    errors.push(`public/help/${file} is missing — run \`npm run build\` to generate it`);
  } else if (!sameContent(actual, expected)) {
    errors.push(
      `public/help/${file} is STALE — it doesn't match the help content. ` +
        `Run \`node scripts/gen-help-manifest.mjs\` (or \`npm run build\`) and commit the result.`
    );
  }
}

if (errors.length) {
  console.error(`[help] route<->help integrity FAILED (${errors.length}):`);
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}
console.log(`[help] route<->help integrity OK: ${routeKeys.size} keyed routes, ${helpComponents.size} help components`);
