#!/usr/bin/env bash
#
# Regenerates ChelseaReviewSummary.md from ChelseaReview.md.
#
# The summary is a progress tracker: topic headings plus one line per item
# (checkbox + CR number + title), with no item bodies. It is DERIVED from the
# full doc — never hand-edit ChelseaReviewSummary.md, or the two will drift.
#
# Run this after adding, removing, renumbering, or re-titling any item:
#     ./generate-summary.sh
#
# Topic counts and the total are computed from the source, so they can't go
# stale. Red (Bug) / blue (Decision) heading colours carry through as-is.
#
# NB: this is bash/awk rather than PowerShell on purpose — Windows PowerShell
# 5.1 parses a UTF-8 script's own literals as ANSI, which mangles the em-dash
# and silently breaks the topic-suffix strip.

set -euo pipefail
cd "$(dirname "$0")"

SRC=ChelseaReview.md
DST=ChelseaReviewSummary.md

[ -f "$SRC" ] || { echo "Source not found: $SRC" >&2; exit 1; }

awk '
  # Everything from the appendix onward is not item content.
  /^## Comparison/ { skip = 1 }
  skip { next }

  /^## / {
    t = $0
    sub(/^## /, "", t)
    if (t == "Topics") next               # the counts table, which we rebuild
    sub(/ — differences from the old system$/, "", t)
    n++
    topic[n] = t
    count[n] = 0
    next
  }

  /^#### / && n > 0 {
    line = $0
    sub(/^#### /, "", line)
    count[n]++
    item[n, count[n]] = line
  }

  END {
    print "# Chelsea Review — Summary"
    print ""
    print "Progress tracker: checkbox + title only. Full detail in [ChelseaReview.md](ChelseaReview.md)."
    print ""
    print "Red = Bug · Blue = needs a decision."
    print ""
    print "☐ open · ☑ fixed in code · ☒ closed / not applicable"
    print ""
    print "> Generated by `generate-summary.sh` — do not hand-edit; re-run the script instead."
    print ""
    print "| Topic | Items |"
    print "|---|:-:|"
    total = 0
    for (i = 1; i <= n; i++) {
      printf "| %s | %d |\n", topic[i], count[i]
      total += count[i]
    }
    printf "| **Total** | **%d** |\n", total

    for (i = 1; i <= n; i++) {
      print ""
      print "---"
      print ""
      printf "## %s\n", topic[i]
      print ""
      for (j = 1; j <= count[i]; j++) printf "- %s\n", item[i, j]
    }
  }
' "$SRC" > "$DST"

printf 'Regenerated %s\n' "$DST"
