//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AddClubTeamRequest {
    clubTeamName: string;
    clubTeamGradYear: string;
    clubTeamLevelOfPlay: string;
}

export interface AddClubTeamResponse {
    clubTeamId: number;
    success: boolean;
    message: string | undefined;
}

export interface AddClubToRepRequest {
    clubName: string;
}

export interface AddClubToRepResponse {
    success: boolean;
    clubName: string;
    similarClubs: ClubSearchResult[] | undefined;
    message: string | undefined;
}

export interface AddressDto {
    streetAddress: string;
    city: string;
    state: string;
    postalCode: string;
}

export interface AgeGroupDto {
    ageGroupId: string;
    ageGroupName: string;
    maxTeams: number;
    registeredCount: number;
    rosterFee: number;
    teamFee: number;
}

export interface AllowedFieldDomainItem {
    name: string;
    displayName: string;
    defaultInputType: string;
    defaultVisibility: string;
    seenInProfiles: number;
}

export interface ApplyDiscountItemDto {
    playerId: string;
    amount: number;
}

export interface ApplyDiscountRequestDto {
    jobId: string;
    familyUserId: string;
    code: string;
    items: ApplyDiscountItemDto[];
}

export interface ApplyDiscountResponseDto {
    success: boolean;
    message: string | undefined;
    totalDiscount: number;
    perPlayer: { [key: string]: number; };
}

export interface AuthTokenResponse {
    accessToken: string;
    refreshToken: string | undefined;
    expiresIn: number | undefined;
}

export interface AvailableTeamDto {
    teamId: string;
    teamName: string;
    agegroupId: string;
    agegroupName: string | undefined;
    divisionId: string | undefined;
    divisionName: string | undefined;
    maxRosterSize: number;
    currentRosterSize: number;
    rosterIsFull: boolean;
    teamAllowsSelfRostering: boolean | undefined;
    agegroupAllowsSelfRostering: boolean | undefined;
    perRegistrantFee: number | undefined;
    perRegistrantDeposit: number | undefined;
    jobUsesWaitlists: boolean;
    waitlistTeamId: string | undefined;
}

export interface CcInfoDto {
    firstName: string | undefined;
    lastName: string | undefined;
    streetAddress: string | undefined;
    zip: string | undefined;
    email: string | undefined;
    phone: string | undefined;
}

export interface ChildDto {
    firstName: string;
    lastName: string;
    gender: string;
    dob: string | undefined;
    email: string | undefined;
    phone: string | undefined;
}

export interface CloneProfileRequest {
    sourceProfileType: string;
}

export interface CloneProfileResult {
    success: boolean;
    newProfileType: string;
    sourceProfileType: string;
    fieldCount: number;
    errorMessage: string | undefined;
}

export interface ClubRepClubDto {
    clubName: string;
    isInUse: boolean;
}

export interface ClubRepRegistrationRequest {
    clubName: string;
    firstName: string;
    lastName: string;
    email: string;
    username: string;
    password: string;
    streetAddress: string;
    city: string;
    state: string;
    postalCode: string;
    cellphone: string;
}

export interface ClubRepRegistrationResponse {
    success: boolean;
    clubId: number | undefined;
    userId: string | undefined;
    message: string | undefined;
    similarClubs: ClubSearchResult[] | undefined;
}

export interface ClubSearchResult {
    clubId: number;
    clubName: string;
    state: string | undefined;
    teamCount: number;
    matchScore: number;
}

export interface ClubTeamDto {
    clubTeamId: number;
    clubTeamName: string;
    clubTeamGradYear: string;
    clubTeamLevelOfPlay: string;
}

export interface CreditCardInfo {
    number: string | undefined;
    expiry: string | undefined;
    code: string | undefined;
    firstName: string | undefined;
    lastName: string | undefined;
    address: string | undefined;
    zip: string | undefined;
    email: string | undefined;
    phone: string | undefined;
}

export interface EmailHealthStatus {
    emailingEnabled: boolean;
    isDevelopment: boolean;
    sandboxMode: boolean;
    sesReachable: boolean;
    max24HourSend: number | undefined;
    sentLast24Hours: number | undefined;
    maxSendRate: number | undefined;
    region: string;
    warning: string | undefined;
}

export interface FamilyPlayerDto {
    playerId: string;
    firstName: string;
    lastName: string;
    gender: string;
    dob: string | undefined;
    registered: boolean;
    selected: boolean;
    priorRegistrations: FamilyPlayerRegistrationDto[];
    defaultFieldValues: { [key: string]: any; } | undefined;
}

export interface FamilyPlayerRegistrationDto {
    registrationId: string;
    active: boolean;
    financials: RegistrationFinancialsDto;
    assignedTeamId: string | undefined;
    assignedTeamName: string | undefined;
    adnSubscriptionId: string | undefined;
    adnSubscriptionStatus: string | undefined;
    adnSubscriptionAmountPerOccurence: number | undefined;
    adnSubscriptionBillingOccurences: number | undefined;
    adnSubscriptionIntervalLength: number | undefined;
    adnSubscriptionStartDate: Date | undefined;
    formFieldValues: { [key: string]: any; };
}

export interface FamilyPlayersResponseDto {
    familyUser: FamilyUserSummaryDto;
    familyPlayers: FamilyPlayerDto[];
    regSaverDetails: RegSaverDetailsDto;
    jobRegForm: JobRegFormDto;
    ccInfo: CcInfoDto;
    jobHasActiveDiscountCodes: boolean;
    jobUsesAmex: boolean;
}

export interface FamilyProfileResponse {
    username: string;
    primary: PersonDto;
    secondary: PersonDto;
    address: AddressDto;
    children: ChildDto[];
}

export interface FamilyRegistrationItemDto {
    registrationId: string;
    playerId: string;
    playerFirstName: string | undefined;
    playerLastName: string | undefined;
    jobId: string;
    jobPath: string;
    assignedTeamId: string | undefined;
    assignedTeamName: string | undefined;
    modified: Date;
    gradYear: string | undefined;
    sportAssnId: string | undefined;
    feeBase: number;
    feeDiscount: number;
    feeDiscountMp: number;
    feeDonation: number;
    feeLatefee: number;
    feeProcessing: number;
    feeTotal: number;
    owedTotal: number;
    paidTotal: number;
}

export interface FamilyRegistrationRequest {
    username: string;
    password: string;
    primary: PersonDto;
    secondary: PersonDto;
    address: AddressDto;
    children: ChildDto[];
}

export interface FamilyRegistrationResponse {
    success: boolean;
    familyUserId: string | undefined;
    familyId: string | undefined;
    message: string | undefined;
}

export interface FamilyUpdateRequest {
    username: string;
    primary: PersonDto;
    secondary: PersonDto;
    address: AddressDto;
    children: ChildDto[];
}

export interface FamilyUserSummaryDto {
    familyUserId: string;
    displayName: string;
    userName: string;
}

export interface FieldCondition {
    field: string;
    value: any | undefined;
    operator: string;
}

export interface FieldValidation {
    required: boolean;
    email: boolean;
    requiredTrue: boolean;
    minLength: number | undefined;
    maxLength: number | undefined;
    pattern: string | undefined;
    min: number | undefined;
    max: number | undefined;
    compare: string | undefined;
    remote: string | undefined;
    message: string | undefined;
}

export interface InsurancePurchaseRequestDto {
    jobId: string;
    familyUserId: string;
    registrationIds: string[];
    quoteIds: string[];
    creditCard: CreditCardInfo;
}

export interface InsurancePurchaseResponseDto {
    success: boolean;
    error: string | undefined;
    policies: { [key: string]: string; };
}

export interface JobMetadataResponse {
    jobId: string;
    jobName: string;
    jobPath: string;
    jobLogoPath: string | undefined;
    jobBannerPath: string | undefined;
    coreRegformPlayer: boolean | undefined;
    usLaxNumberValidThroughDate: Date | undefined;
    expiryUsers: Date | undefined;
    playerProfileMetadataJson: string | undefined;
    jsonOptions: string | undefined;
    momLabel: string | undefined;
    dadLabel: string | undefined;
    playerRegReleaseOfLiability: string | undefined;
    playerRegCodeOfConduct: string | undefined;
    playerRegCovid19Waiver: string | undefined;
    playerRegRefundPolicy: string | undefined;
    offerPlayerRegsaverInsurance: boolean;
    adnArb: boolean | undefined;
    adnArbBillingOccurences: number | undefined;
    adnArbIntervalLength: number | undefined;
    adnArbStartDate: Date | undefined;
}

export interface JobRegFieldDto {
    name: string;
    dbColumn: string;
    displayName: string;
    inputType: string;
    dataSource: string | undefined;
    options: ProfileFieldOption[] | undefined;
    validation: FieldValidation;
    order: number;
    visibility: string;
    computed: boolean;
    conditionalOn: FieldCondition;
}

export interface JobRegFormDto {
    version: string;
    coreProfileName: string | undefined;
    fields: JobRegFieldDto[];
    waiverFieldNames: string[];
    constraintType: string | undefined;
}

export interface LoginRequest {
    username: string;
    password: string;
}

export interface LoginResponseDto {
    userId: string;
    registrations: RegistrationRoleDto[];
}

export interface MigrateAllRequest {
    dryRun: boolean;
    profileTypes: string[] | undefined;
}

export interface MigrateProfilesRequest {
    dryRun: boolean;
    profileTypes: string[] | undefined;
}

export interface MigrationReport {
    successCount: number;
    failureCount: number;
    warningCount: number;
    skippedCount: number;
    startedAt: Date;
    completedAt: Date | undefined;
    results: MigrationResult[];
    globalWarnings: string[];
}

export interface MigrationResult {
    jobId: string;
    jobName: string;
    profileType: string;
    success: boolean;
    errorMessage: string | undefined;
    warnings: string[];
    fieldCount: number;
    generatedMetadata: ProfileMetadata;
}

export interface NextProfileTypeResult {
    newProfileType: string;
}

export interface OptionSet {
    key: string;
    provider: string;
    readOnly: boolean;
    values: ProfileFieldOption[];
}

export interface OptionSetUpdateRequest {
    values: ProfileFieldOption[];
}

export enum PaymentOption {
    _0 = 0,
    _1 = 1,
    _2 = 2,
}

export interface PaymentRequestDto {
    jobId: string;
    familyUserId: string;
    paymentOption: PaymentOption;
    creditCard: CreditCardInfo;
    idempotencyKey: string | undefined;
    viConfirmed: boolean | undefined;
    viPolicyNumber: string | undefined;
    viPolicyCreateDate: Date | undefined;
    viQuoteIds: string[] | undefined;
    viToken: string | undefined;
}

export interface PaymentResponseDto {
    success: boolean;
    message: string | undefined;
    errorCode: string | undefined;
    transactionId: string | undefined;
    subscriptionId: string | undefined;
    subscriptionIds: { [key: string]: string; } | undefined;
    failedSubscriptionIds: string[] | undefined;
    readonly partialSuccess: boolean;
}

export interface PersonDto {
    firstName: string;
    lastName: string;
    cellphone: string;
    email: string;
}

export interface PlayerRegConfirmationDto {
    tsic: PlayerRegTsicFinancialDto;
    insurance: PlayerRegInsuranceStatusDto;
    confirmationHtml: string;
}

export interface PlayerRegFinancialLineDto {
    registrationId: string;
    playerName: string;
    teamName: string;
    feeTotal: number;
    discountCodes: string[];
}

export interface PlayerRegInsuranceStatusDto {
    offered: boolean;
    selected: boolean;
    declined: boolean;
    purchaseSucceeded: boolean;
    policies: PlayerRegPolicyDto[];
}

export interface PlayerRegPolicyDto {
    registrationId: string;
    policyNumber: string;
    issuedUtc: Date;
    insurableAmountCents: number;
}

export interface PlayerRegTsicFinancialDto {
    wasImmediateCharge: boolean;
    wasArb: boolean;
    amountCharged: number;
    currency: string;
    transactionId: string | undefined;
    paymentMethodMasked: string | undefined;
    nextArbBillDate: Date | undefined;
    totalOriginal: number;
    totalDiscounts: number;
    totalNet: number;
    lines: PlayerRegFinancialLineDto[];
}

export interface PreSubmitInsuranceDto {
    available: boolean;
    playerObject: VIPlayerObjectResponse;
    error: string | undefined;
    expiresUtc: Date | undefined;
    stateId: string | undefined;
}

export interface PreSubmitPlayerRegistrationRequestDto {
    jobPath: string;
    familyUserId: string;
    teamSelections: PreSubmitTeamSelectionDto[];
}

export interface PreSubmitPlayerRegistrationResponseDto {
    teamResults: PreSubmitTeamResultDto[];
    readonly hasFullTeams: boolean;
    nextTab: string;
    insurance: PreSubmitInsuranceDto;
    validationErrors: PreSubmitValidationErrorDto[] | undefined;
}

export interface PreSubmitTeamResultDto {
    playerId: string;
    teamId: string;
    isFull: boolean;
    teamName: string;
    message: string;
    registrationCreated: boolean;
}

export interface PreSubmitTeamSelectionDto {
    playerId: string;
    teamId: string;
    formValues: { [key: string]: any; } | undefined;
}

export interface PreSubmitValidationErrorDto {
    playerId: string;
    field: string;
    message: string;
}

export interface ProblemDetails {
    type: string | undefined;
    title: string | undefined;
    status: number | undefined;
    detail: string | undefined;
    instance: string | undefined;

    [key: string]: any;
}

export interface ProfileBatchMigrationReport {
    startedAt: Date;
    completedAt: Date | undefined;
    totalProfiles: number;
    successCount: number;
    failureCount: number;
    totalJobsAffected: number;
    results: ProfileMigrationResult[];
    globalWarnings: string[];
}

export interface ProfileFieldOption {
    value: string;
    label: string;
}

export interface ProfileMetadata {
    fields: ProfileMetadataField[];
    source: ProfileMetadataSource;
}

export interface ProfileMetadataField {
    name: string;
    dbColumn: string;
    displayName: string;
    inputType: string;
    dataSource: string | undefined;
    options: ProfileFieldOption[] | undefined;
    validation: FieldValidation;
    order: number;
    visibility: string;
    computed: boolean;
    conditionalOn: FieldCondition;
}

export interface ProfileMetadataSource {
    sourceFile: string;
    repository: string;
    commitSha: string;
    migratedAt: Date;
    migratedBy: string;
}

export interface ProfileMetadataWithOptions {
    jobId: string;
    jobName: string;
    metadata: ProfileMetadata;
    jsonOptions: { [key: string]: any; } | undefined;
}

export interface ProfileMigrationResult {
    profileType: string;
    success: boolean;
    fieldCount: number;
    jobsAffected: number;
    affectedJobIds: string[];
    affectedJobNames: string[];
    affectedJobYears: string[];
    generatedMetadata: ProfileMetadata;
    warnings: string[];
    errorMessage: string | undefined;
}

export interface ProfileSummary {
    profileType: string;
    jobCount: number;
    migratedJobCount: number;
    allJobsMigrated: boolean;
    sampleJobNames: string[];
}

export interface RefreshTokenRequest {
    refreshToken: string;
}

export interface RegSaverDetailsDto {
    policyNumber: string;
    policyCreateDate: Date;
}

export interface RegisterTeamRequest {
    clubTeamId: number;
    jobPath: string;
    ageGroupId: string | undefined;
}

export interface RegisterTeamResponse {
    teamId: string;
    success: boolean;
    message: string | undefined;
}

export interface RegisteredTeamDto {
    teamId: string;
    clubTeamId: number;
    clubTeamName: string;
    clubTeamGradYear: string;
    clubTeamLevelOfPlay: string;
    ageGroupId: string;
    ageGroupName: string;
    feeBase: number;
    feeProcessing: number;
    feeTotal: number;
    paidTotal: number;
    owedTotal: number;
}

export interface RegistrationDto {
    regId: string;
    displayText: string;
    jobLogo: string;
    jobPath: string | undefined;
}

export interface RegistrationFinancialsDto {
    feeBase: number;
    feeProcessing: number;
    feeDiscount: number;
    feeDonation: number;
    feeLateFee: number;
    feeTotal: number;
    owedTotal: number;
    paidTotal: number;
}

export interface RegistrationRoleDto {
    roleName: string;
    roleRegistrations: RegistrationDto[];
}

export interface RegistrationStatusRequest {
    jobPath: string;
    registrationTypes: string[];
}

export interface RegistrationStatusResponse {
    registrationType: string;
    isAvailable: boolean;
    message: string | undefined;
    registrationUrl: string | undefined;
}

export interface RenameOptionSetRequest {
    newKey: string;
}

export interface RoleSelectionRequest {
    regId: string;
}

export interface TeamsMetadataResponse {
    clubId: number;
    clubName: string;
    availableClubTeams: ClubTeamDto[];
    registeredTeams: RegisteredTeamDto[];
    ageGroups: AgeGroupDto[];
}

export interface TestValidationRequest {
    field: ProfileMetadataField;
    testValue: string;
}

export interface UpdateCurrentJobProfileConfigRequest {
    profileType: string;
    teamConstraint: string;
}

export interface VIColorsDto {
    background: string;
    primary: string;
    primary_contrast: string;
    secondary: string;
    secondary_contrast: string;
    neutral: string;
    neutral_contrast: string;
    error: string;
    error_contrast: string;
    success: string;
    success_contrast: string;
    border: string;
}

export interface VIComponentsDto {
    border_radius: string;
}

export interface VICustomerDto {
    first_name: string;
    last_name: string;
    email_address: string;
    phone: string;
    street: string;
    city: string;
    state: string;
    postal_code: string;
}

export interface VIOrganizationDto {
    org_name: string;
    org_contact_email: string;
    org_contact_first_name: string;
    org_contact_last_name: string;
    org_contact_phone: string;
    org_website: string;
    org_city: string;
    org_state: string;
    org_postal_code: string;
    org_country: string;
    payment_plan: boolean;
    registration_session_name: string;
}

export interface VIParticipantDto {
    first_name: string;
    last_name: string;
}

export interface VIPaymentsDto {
    enabled: boolean;
    button: boolean;
}

export interface VIPlayerMetadataDto {
    context_name: string;
    context_event: string;
    context_description: string;
    tsic_registrationid: string;
    tsic_secondchance: string;
    tsic_customer: string;
}

export interface VIPlayerObjectResponse {
    client_id: string;
    theme: VIThemeDto;
    product_config: VIPlayerProductConfigDto;
    payments: VIPaymentsDto;
}

export interface VIPlayerPolicyAttributes {
    event_start_date: Date | undefined;
    event_end_date: Date | undefined;
    insurable_amount: number;
    participant: VIParticipantDto;
    organization: VIOrganizationDto;
}

export interface VIPlayerProductConfigDto {
    "registration-cancellation": VIPlayerProductDto[];
}

export interface VIPlayerProductDto {
    customer: VICustomerDto;
    metadata: VIPlayerMetadataDto;
    policy_attributes: VIPlayerPolicyAttributes;
    offer_Id: string;
}

export interface VIThemeDto {
    colors: VIColorsDto;
    font_family: string;
    components: VIComponentsDto;
}

export interface ValidationTestResult {
    fieldName: string;
    testValue: string;
    isValid: boolean;
    messages: string[];
}