//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AddressDto {
    streetAddress?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    postalCode?: string | undefined;
}

export interface AllowedFieldDomainItem {
    name?: string | undefined;
    displayName?: string | undefined;
    defaultInputType?: string | undefined;
    defaultVisibility?: string | undefined;
    seenInProfiles?: number;
}

export interface ApplyDiscountItemDto {
    playerId: string;
    amount?: number;
}

export interface ApplyDiscountRequestDto {
    jobId: string;
    familyUserId: string;
    code: string;
    items: ApplyDiscountItemDto[];
}

export interface ApplyDiscountResponseDto {
    success?: boolean;
    message?: string | undefined;
    totalDiscount?: number;
    perPlayer?: { [key: string]: number; } | undefined;
}

export interface AuthTokenResponse {
    accessToken?: string | undefined;
    refreshToken?: string | undefined;
    expiresIn?: number | undefined;
}

export interface AvailableTeamDto {
    teamId: string;
    teamName: string | undefined;
    agegroupId?: string;
    agegroupName?: string | undefined;
    divisionId?: string | undefined;
    divisionName?: string | undefined;
    maxRosterSize?: number;
    currentRosterSize?: number;
    rosterIsFull?: boolean;
    teamAllowsSelfRostering?: boolean | undefined;
    agegroupAllowsSelfRostering?: boolean | undefined;
    perRegistrantFee?: number | undefined;
    perRegistrantDeposit?: number | undefined;
    jobUsesWaitlists?: boolean;
    waitlistTeamId?: string | undefined;
}

export interface CcInfoDto {
    firstName?: string | undefined;
    lastName?: string | undefined;
    streetAddress?: string | undefined;
    zip?: string | undefined;
    email?: string | undefined;
    phone?: string | undefined;
}

export interface ChildDto {
    firstName?: string | undefined;
    lastName?: string | undefined;
    gender?: string | undefined;
    dob?: string | undefined;
    email?: string | undefined;
    phone?: string | undefined;
}

export interface CloneProfileRequest {
    sourceProfileType?: string | undefined;
}

export interface CloneProfileResult {
    success?: boolean;
    newProfileType?: string | undefined;
    sourceProfileType?: string | undefined;
    fieldCount?: number;
    errorMessage?: string | undefined;
}

export interface ClubRegistrationRequest {
    clubName?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    email?: string | undefined;
    username?: string | undefined;
    password?: string | undefined;
    streetAddress?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    postalCode?: string | undefined;
    cellphone?: string | undefined;
}

export interface ClubRegistrationResponse {
    success?: boolean;
    clubId?: number | undefined;
    userId?: string | undefined;
    message?: string | undefined;
    similarClubs?: ClubSearchResult[] | undefined;
}

export interface ClubSearchResult {
    clubId?: number;
    clubName?: string | undefined;
    state?: string | undefined;
    teamCount?: number;
    matchScore?: number;
}

export interface CreditCardInfo {
    number?: string | undefined;
    expiry?: string | undefined;
    code?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    address?: string | undefined;
    zip?: string | undefined;
    email?: string | undefined;
    phone?: string | undefined;
}

export interface EmailHealthStatus {
    emailingEnabled?: boolean;
    isDevelopment?: boolean;
    sandboxMode?: boolean;
    sesReachable?: boolean;
    max24HourSend?: number | undefined;
    sentLast24Hours?: number | undefined;
    maxSendRate?: number | undefined;
    region?: string | undefined;
    warning?: string | undefined;
}

export interface FamilyPlayerDto {
    playerId?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    gender?: string | undefined;
    dob?: string | undefined;
    registered?: boolean;
    selected?: boolean;
    priorRegistrations?: FamilyPlayerRegistrationDto[] | undefined;
    defaultFieldValues?: { [key: string]: any; } | undefined;
}

export interface FamilyPlayerRegistrationDto {
    registrationId?: string;
    active?: boolean;
    financials?: RegistrationFinancialsDto;
    assignedTeamId?: string | undefined;
    assignedTeamName?: string | undefined;
    adnSubscriptionId?: string | undefined;
    adnSubscriptionStatus?: string | undefined;
    adnSubscriptionAmountPerOccurence?: number | undefined;
    adnSubscriptionBillingOccurences?: number | undefined;
    adnSubscriptionIntervalLength?: number | undefined;
    adnSubscriptionStartDate?: Date | undefined;
    formFieldValues?: { [key: string]: any; } | undefined;
}

export interface FamilyPlayersResponseDto {
    familyUser?: FamilyUserSummaryDto;
    familyPlayers?: FamilyPlayerDto[] | undefined;
    regSaverDetails?: RegSaverDetailsDto;
    jobRegForm?: JobRegFormDto;
    ccInfo?: CcInfoDto;
    jobHasActiveDiscountCodes?: boolean;
    jobUsesAmex?: boolean;
}

export interface FamilyProfileResponse {
    username?: string | undefined;
    primary?: PersonDto;
    secondary?: PersonDto;
    address?: AddressDto;
    children?: ChildDto[] | undefined;
}

export interface FamilyRegistrationItemDto {
    registrationId?: string;
    playerId?: string | undefined;
    playerFirstName?: string | undefined;
    playerLastName?: string | undefined;
    jobId?: string;
    jobPath?: string | undefined;
    assignedTeamId?: string | undefined;
    assignedTeamName?: string | undefined;
    modified?: Date;
    gradYear?: string | undefined;
    sportAssnId?: string | undefined;
    feeBase?: number;
    feeDiscount?: number;
    feeDiscountMp?: number;
    feeDonation?: number;
    feeLatefee?: number;
    feeProcessing?: number;
    feeTotal?: number;
    owedTotal?: number;
    paidTotal?: number;
}

export interface FamilyRegistrationRequest {
    username?: string | undefined;
    password?: string | undefined;
    primary?: PersonDto;
    secondary?: PersonDto;
    address?: AddressDto;
    children?: ChildDto[] | undefined;
}

export interface FamilyRegistrationResponse {
    success?: boolean;
    familyUserId?: string | undefined;
    familyId?: string | undefined;
    message?: string | undefined;
}

export interface FamilyUpdateRequest {
    username?: string | undefined;
    primary?: PersonDto;
    secondary?: PersonDto;
    address?: AddressDto;
    children?: ChildDto[] | undefined;
}

export interface FamilyUserSummaryDto {
    familyUserId?: string | undefined;
    displayName?: string | undefined;
    userName?: string | undefined;
}

export interface FieldCondition {
    field?: string | undefined;
    value?: any | undefined;
    operator?: string | undefined;
}

export interface FieldValidation {
    required?: boolean;
    email?: boolean;
    requiredTrue?: boolean;
    minLength?: number | undefined;
    maxLength?: number | undefined;
    pattern?: string | undefined;
    min?: number | undefined;
    max?: number | undefined;
    compare?: string | undefined;
    remote?: string | undefined;
    message?: string | undefined;
}

export interface InsurancePurchaseRequestDto {
    jobId: string;
    familyUserId: string;
    registrationIds: string[];
    quoteIds: string[];
    creditCard?: CreditCardInfo;
}

export interface InsurancePurchaseResponseDto {
    success?: boolean;
    error?: string | undefined;
    policies?: { [key: string]: string; } | undefined;
}

export interface JobMetadataResponse {
    jobId: string;
    jobName: string | undefined;
    jobPath: string | undefined;
    jobLogoPath?: string | undefined;
    jobBannerPath?: string | undefined;
    coreRegformPlayer?: boolean | undefined;
    usLaxNumberValidThroughDate?: Date | undefined;
    expiryUsers?: Date | undefined;
    playerProfileMetadataJson?: string | undefined;
    jsonOptions?: string | undefined;
    momLabel?: string | undefined;
    dadLabel?: string | undefined;
    playerRegReleaseOfLiability?: string | undefined;
    playerRegCodeOfConduct?: string | undefined;
    playerRegCovid19Waiver?: string | undefined;
    playerRegRefundPolicy?: string | undefined;
    offerPlayerRegsaverInsurance?: boolean;
    adnArb?: boolean | undefined;
    adnArbBillingOccurences?: number | undefined;
    adnArbIntervalLength?: number | undefined;
    adnArbStartDate?: Date | undefined;
}

export interface JobRegFieldDto {
    name?: string | undefined;
    dbColumn?: string | undefined;
    displayName?: string | undefined;
    inputType?: string | undefined;
    dataSource?: string | undefined;
    options?: ProfileFieldOption[] | undefined;
    validation?: FieldValidation;
    order?: number;
    visibility?: string | undefined;
    computed?: boolean;
    conditionalOn?: FieldCondition;
}

export interface JobRegFormDto {
    version?: string | undefined;
    coreProfileName?: string | undefined;
    fields?: JobRegFieldDto[] | undefined;
    waiverFieldNames?: string[] | undefined;
    constraintType?: string | undefined;
}

export interface LoginRequest {
    username?: string | undefined;
    password?: string | undefined;
}

export interface LoginResponseDto {
    userId?: string | undefined;
    registrations?: RegistrationRoleDto[] | undefined;
}

export interface MigrateAllRequest {
    dryRun?: boolean;
    profileTypes?: string[] | undefined;
}

export interface MigrateProfilesRequest {
    dryRun?: boolean;
    profileTypes?: string[] | undefined;
}

export interface MigrationReport {
    successCount?: number;
    failureCount?: number;
    warningCount?: number;
    skippedCount?: number;
    startedAt?: Date;
    completedAt?: Date | undefined;
    results?: MigrationResult[] | undefined;
    globalWarnings?: string[] | undefined;
}

export interface MigrationResult {
    jobId: string;
    jobName?: string | undefined;
    profileType?: string | undefined;
    success?: boolean;
    errorMessage?: string | undefined;
    warnings?: string[] | undefined;
    fieldCount?: number;
    generatedMetadata?: ProfileMetadata;
}

export interface NextProfileTypeResult {
    newProfileType?: string | undefined;
}

export interface OptionSet {
    key?: string | undefined;
    provider?: string | undefined;
    readOnly?: boolean;
    values?: ProfileFieldOption[] | undefined;
}

export interface OptionSetUpdateRequest {
    values?: ProfileFieldOption[] | undefined;
}

export enum PaymentOption {
    _0 = 0,
    _1 = 1,
    _2 = 2,
}

export interface PaymentRequestDto {
    jobId: string;
    familyUserId: string;
    paymentOption: PaymentOption;
    creditCard?: CreditCardInfo;
    idempotencyKey?: string | undefined;
    viConfirmed?: boolean | undefined;
    viPolicyNumber?: string | undefined;
    viPolicyCreateDate?: Date | undefined;
    viQuoteIds?: string[] | undefined;
    viToken?: string | undefined;
}

export interface PaymentResponseDto {
    success?: boolean;
    message?: string | undefined;
    errorCode?: string | undefined;
    transactionId?: string | undefined;
    subscriptionId?: string | undefined;
    subscriptionIds?: { [key: string]: string; } | undefined;
    failedSubscriptionIds?: string[] | undefined;
    readonly partialSuccess?: boolean;
}

export interface PersonDto {
    firstName?: string | undefined;
    lastName?: string | undefined;
    cellphone?: string | undefined;
    email?: string | undefined;
}

export interface PlayerRegConfirmationDto {
    tsic?: PlayerRegTsicFinancialDto;
    insurance?: PlayerRegInsuranceStatusDto;
    confirmationHtml?: string | undefined;
}

export interface PlayerRegFinancialLineDto {
    registrationId?: string;
    playerName?: string | undefined;
    teamName?: string | undefined;
    feeTotal?: number;
    discountCodes?: string[] | undefined;
}

export interface PlayerRegInsuranceStatusDto {
    offered?: boolean;
    selected?: boolean;
    declined?: boolean;
    purchaseSucceeded?: boolean;
    policies?: PlayerRegPolicyDto[] | undefined;
}

export interface PlayerRegPolicyDto {
    registrationId?: string;
    policyNumber?: string | undefined;
    issuedUtc?: Date;
    insurableAmountCents?: number;
}

export interface PlayerRegTsicFinancialDto {
    wasImmediateCharge?: boolean;
    wasArb?: boolean;
    amountCharged?: number;
    currency?: string | undefined;
    transactionId?: string | undefined;
    paymentMethodMasked?: string | undefined;
    nextArbBillDate?: Date | undefined;
    totalOriginal?: number;
    totalDiscounts?: number;
    totalNet?: number;
    lines?: PlayerRegFinancialLineDto[] | undefined;
}

export interface PreSubmitInsuranceDto {
    available?: boolean;
    playerObject?: VIPlayerObjectResponse;
    error?: string | undefined;
    expiresUtc?: Date | undefined;
    stateId?: string | undefined;
}

export interface PreSubmitRegistrationRequestDto {
    jobPath?: string | undefined;
    familyUserId?: string | undefined;
    teamSelections?: PreSubmitTeamSelectionDto[] | undefined;
}

export interface PreSubmitRegistrationResponseDto {
    teamResults?: PreSubmitTeamResultDto[] | undefined;
    readonly hasFullTeams?: boolean;
    nextTab?: string | undefined;
    insurance?: PreSubmitInsuranceDto;
    validationErrors?: PreSubmitValidationErrorDto[] | undefined;
}

export interface PreSubmitTeamResultDto {
    playerId?: string | undefined;
    teamId?: string;
    isFull?: boolean;
    teamName?: string | undefined;
    message?: string | undefined;
    registrationCreated?: boolean;
}

export interface PreSubmitTeamSelectionDto {
    playerId?: string | undefined;
    teamId?: string;
    formValues?: { [key: string]: any; } | undefined;
}

export interface PreSubmitValidationErrorDto {
    playerId?: string | undefined;
    field?: string | undefined;
    message?: string | undefined;
}

export interface ProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export interface ProfileBatchMigrationReport {
    startedAt?: Date;
    completedAt?: Date | undefined;
    totalProfiles?: number;
    successCount?: number;
    failureCount?: number;
    totalJobsAffected?: number;
    results?: ProfileMigrationResult[] | undefined;
    globalWarnings?: string[] | undefined;
}

export interface ProfileFieldOption {
    value?: string | undefined;
    label?: string | undefined;
}

export interface ProfileMetadata {
    fields?: ProfileMetadataField[] | undefined;
    source?: ProfileMetadataSource;
}

export interface ProfileMetadataField {
    name?: string | undefined;
    dbColumn?: string | undefined;
    displayName?: string | undefined;
    inputType?: string | undefined;
    dataSource?: string | undefined;
    options?: ProfileFieldOption[] | undefined;
    validation?: FieldValidation;
    order: number;
    visibility?: string | undefined;
    computed: boolean;
    conditionalOn?: FieldCondition;
}

export interface ProfileMetadataSource {
    sourceFile?: string | undefined;
    repository?: string | undefined;
    commitSha?: string | undefined;
    migratedAt?: Date;
    migratedBy?: string | undefined;
}

export interface ProfileMetadataWithOptions {
    jobId?: string;
    jobName?: string | undefined;
    metadata?: ProfileMetadata;
    jsonOptions?: { [key: string]: any; } | undefined;
}

export interface ProfileMigrationResult {
    profileType?: string | undefined;
    success?: boolean;
    fieldCount?: number;
    jobsAffected?: number;
    affectedJobIds?: string[] | undefined;
    affectedJobNames?: string[] | undefined;
    affectedJobYears?: string[] | undefined;
    generatedMetadata?: ProfileMetadata;
    warnings?: string[] | undefined;
    errorMessage?: string | undefined;
}

export interface ProfileSummary {
    profileType?: string | undefined;
    jobCount?: number;
    migratedJobCount?: number;
    allJobsMigrated?: boolean;
    sampleJobNames?: string[] | undefined;
}

export interface RefreshTokenRequest {
    refreshToken?: string | undefined;
}

export interface RegSaverDetailsDto {
    policyNumber?: string | undefined;
    policyCreateDate?: Date;
}

export interface RegistrationDto {
    regId?: string | undefined;
    displayText?: string | undefined;
    jobLogo?: string | undefined;
    jobPath?: string | undefined;
}

export interface RegistrationFinancialsDto {
    feeBase?: number;
    feeProcessing?: number;
    feeDiscount?: number;
    feeDonation?: number;
    feeLateFee?: number;
    feeTotal?: number;
    owedTotal?: number;
    paidTotal?: number;
}

export interface RegistrationRoleDto {
    roleName?: string | undefined;
    roleRegistrations?: RegistrationDto[] | undefined;
}

export interface RegistrationStatusRequest {
    jobPath: string | undefined;
    registrationTypes: string[] | undefined;
}

export interface RegistrationStatusResponse {
    registrationType: string | undefined;
    isAvailable: boolean;
    message?: string | undefined;
    registrationUrl?: string | undefined;
}

export interface RenameOptionSetRequest {
    newKey?: string | undefined;
}

export interface RoleSelectionRequest {
    regId?: string | undefined;
}

export interface TestValidationRequest {
    field?: ProfileMetadataField;
    testValue?: string | undefined;
}

export interface UpdateCurrentJobProfileConfigRequest {
    profileType?: string | undefined;
    teamConstraint?: string | undefined;
}

export interface VIColorsDto {
    background?: string | undefined;
    primary?: string | undefined;
    primary_contrast?: string | undefined;
    secondary?: string | undefined;
    secondary_contrast?: string | undefined;
    neutral?: string | undefined;
    neutral_contrast?: string | undefined;
    error?: string | undefined;
    error_contrast?: string | undefined;
    success?: string | undefined;
    success_contrast?: string | undefined;
    border?: string | undefined;
}

export interface VIComponentsDto {
    border_radius?: string | undefined;
}

export interface VICustomerDto {
    first_name?: string | undefined;
    last_name?: string | undefined;
    email_address?: string | undefined;
    phone?: string | undefined;
    street?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    postal_code?: string | undefined;
}

export interface VIOrganizationDto {
    org_name?: string | undefined;
    org_contact_email?: string | undefined;
    org_contact_first_name?: string | undefined;
    org_contact_last_name?: string | undefined;
    org_contact_phone?: string | undefined;
    org_website?: string | undefined;
    org_city?: string | undefined;
    org_state?: string | undefined;
    org_postal_code?: string | undefined;
    org_country?: string | undefined;
    payment_plan?: boolean;
    registration_session_name?: string | undefined;
}

export interface VIParticipantDto {
    first_name?: string | undefined;
    last_name?: string | undefined;
}

export interface VIPaymentsDto {
    enabled?: boolean;
    button?: boolean;
}

export interface VIPlayerMetadataDto {
    context_name?: string | undefined;
    context_event?: string | undefined;
    context_description?: string | undefined;
    tsic_registrationid?: string;
    tsic_secondchance?: string | undefined;
    tsic_customer?: string | undefined;
}

export interface VIPlayerObjectResponse {
    client_id?: string | undefined;
    theme: VIThemeDto;
    product_config?: VIPlayerProductConfigDto;
    payments?: VIPaymentsDto;
}

export interface VIPlayerPolicyAttributes {
    event_start_date?: Date | undefined;
    event_end_date?: Date | undefined;
    insurable_amount?: number;
    participant?: VIParticipantDto;
    organization?: VIOrganizationDto;
}

export interface VIPlayerProductConfigDto {
    "registration-cancellation"?: VIPlayerProductDto[] | undefined;
}

export interface VIPlayerProductDto {
    customer?: VICustomerDto;
    metadata?: VIPlayerMetadataDto;
    policy_attributes?: VIPlayerPolicyAttributes;
    offer_Id?: string | undefined;
}

export interface VIThemeDto {
    colors?: VIColorsDto;
    font_family?: string | undefined;
    components?: VIComponentsDto;
}

export interface ValidationTestResult {
    fieldName?: string | undefined;
    testValue?: string | undefined;
    isValid?: boolean;
    messages?: string[] | undefined;
}