/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type UpdateJobConfigRequest = {
    jobId: string;
    updatedOn: string | null;
    jobName: string | null;
    displayName: string | null;
    jobDescription: string | null;
    jobTagline: string | null;
    jobCode: string | null;
    year: string | null;
    season: string | null;
    jobTypeId: number;
    sportId: string;
    billingTypeId: number;
    expiryAdmin: string;
    expiryUsers: string;
    eventStartDate: string | null;
    eventEndDate: string | null;
    searchenginKeywords: string | null;
    searchengineDescription: string | null;
    bBannerIsCustom: boolean;
    bannerFile: string | null;
    mobileJobName: string | null;
    jobNameQbp: string | null;
    momLabel: string | null;
    dadLabel: string | null;
    bSuspendPublic: boolean;
    bRegistrationAllowPlayer: boolean | null;
    bRegistrationAllowTeam: boolean | null;
    bAllowMobileRegn: boolean | null;
    bUseWaitlists: boolean;
    bRestrictPlayerTeamsToAgerange: boolean | null;
    bOfferPlayerRegsaverInsurance: boolean | null;
    bOfferTeamRegsaverInsurance: boolean | null;
    playerRegMultiPlayerDiscountMin: number;
    playerRegMultiPlayerDiscountPercent: number;
    coreRegformPlayer: string | null;
    regformNamePlayer: string;
    regformNameTeam: string;
    regformNameCoach: string;
    regformNameClubRep: string;
    playerProfileMetadataJson: string | null;
    uslaxNumberValidThroughDate: string | null;
    paymentMethodsAllowedCode: number;
    bAddProcessingFees: boolean;
    processingFeePercent: number;
    bApplyProcessingFeesToTeamDeposit: boolean | null;
    bTeamsFullPaymentRequired: boolean | null;
    balancedueaspercent: string | null;
    bAllowRefundsInPriorMonths: boolean | null;
    bAllowCreditAll: boolean | null;
    payTo: string | null;
    mailTo: string | null;
    mailinPaymentWarning: string | null;
    adnArb: boolean | null;
    adnArbbillingOccurences: number;
    adnArbintervalLength: number;
    adnArbstartDate: string | null;
    adnArbMinimunTotalCharge: number;
    regFormFrom: string | null;
    regFormCcs: string | null;
    regFormBccs: string | null;
    rescheduleemaillist: string | null;
    alwayscopyemaillist: string | null;
    bDisallowCcplayerConfirmations: boolean | null;
    playerRegConfirmationEmail: string | null;
    playerRegConfirmationOnScreen: string | null;
    playerRegRefundPolicy: string | null;
    playerRegReleaseOfLiability: string | null;
    playerRegCodeOfConduct: string | null;
    playerRegCovid19Waiver: string | null;
    adultRegConfirmationEmail: string | null;
    adultRegConfirmationOnScreen: string | null;
    adultRegRefundPolicy: string | null;
    adultRegReleaseOfLiability: string | null;
    adultRegCodeOfConduct: string | null;
    refereeRegConfirmationEmail: string | null;
    refereeRegConfirmationOnScreen: string | null;
    recruiterRegConfirmationEmail: string | null;
    recruiterRegConfirmationOnScreen: string | null;
    bClubRepAllowEdit: boolean | null;
    bClubRepAllowDelete: boolean | null;
    bClubRepAllowAdd: boolean | null;
    bAllowMobileLogin: boolean;
    bAllowRosterViewAdult: boolean;
    bAllowRosterViewPlayer: boolean;
    bShowTeamNameOnlyInSchedules: boolean;
    bScheduleAllowPublicAccess: boolean | null;
    bTeamPushDirectors: boolean | null;
    bEnableTsicteams: boolean | null;
    bEnableMobileRsvp: boolean | null;
    bEnableMobileTeamChat: boolean | null;
    benableStp: boolean | null;
    bEnableStore: boolean | null;
    bSignalRschedule: boolean | null;
    mobileScoreHoursPastGameEligible: number;
    storeSalesTax: number;
    storeRefundPolicy: string | null;
    storePickupDetails: string | null;
    storeContactEmail: string | null;
    storeTsicrate: number;
};

