# ============================================================================
# Export-WidgetConfig.ps1
#
# Exports the current dev widget configuration as an idempotent SQL script.
# The output script can be run against any database (fresh or prod-restore)
# to stand up the full widget system with dev's current configuration.
#
# What it produces:
#   1. Schema + table DDL (IF NOT EXISTS)
#   2. Schema migration (Section -> Workspace, constraint updates)
#   3. MERGE statements for WidgetCategory, Widget, WidgetDefault, JobWidget
#
# Usage:
#   .\scripts\Export-WidgetConfig.ps1                          # uses appsettings
#   .\scripts\Export-WidgetConfig.ps1 -ConnectionString "..."  # explicit
#   .\scripts\Export-WidgetConfig.ps1 -OutputPath ".\my.sql"   # custom output
#
# Workflow:
#   1. Configure widgets in dev via Widget Editor
#   2. Run this script to snapshot dev config
#   3. Run the output SQL against target DB (prod, restored backup, etc.)
# ============================================================================

param(
    [string]$ConnectionString,
    [string]$OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Resolve connection string ──
if (-not $ConnectionString) {
    $apiDir = Join-Path $PSScriptRoot '..\TSIC-Core-Angular\src\backend\TSIC.API'
    $settingsFile = Join-Path $apiDir 'appsettings.Development.json'
    if (-not (Test-Path $settingsFile)) {
        $settingsFile = Join-Path $apiDir 'appsettings.json'
    }
    if (-not (Test-Path $settingsFile)) {
        Write-Error "Cannot find appsettings. Use -ConnectionString parameter."
        return
    }
    $settings = Get-Content $settingsFile -Raw | ConvertFrom-Json
    $ConnectionString = $settings.ConnectionStrings.DefaultConnection
    Write-Host "Using connection: $($ConnectionString -replace 'Password=[^;]+','Password=***')" -ForegroundColor Cyan
}

# ── Resolve output path ──
if (-not $OutputPath) {
    $OutputPath = Join-Path $PSScriptRoot 'deploy-widget-config.sql'
}

# ── Helper: run a query and return DataTable ──
function Invoke-Sql {
    param([string]$Query)
    $conn = New-Object System.Data.SqlClient.SqlConnection($ConnectionString)
    $conn.Open()
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $Query
    $adapter = New-Object System.Data.SqlClient.SqlDataAdapter($cmd)
    $table = New-Object System.Data.DataTable
    $adapter.Fill($table) | Out-Null
    $conn.Close()
    return $table
}

# ── Helper: escape SQL string ──
function Esc([string]$val) {
    if ($null -eq $val) { return 'NULL' }
    return "N'" + $val.Replace("'", "''") + "'"
}

# ── Helper: nullable int ──
function IntOrNull($val) {
    if ($null -eq $val -or $val -is [System.DBNull]) { return 'NULL' }
    return [string]$val
}

# ── Helper: nullable string ──
function StrOrNull($val) {
    if ($null -eq $val -or $val -is [System.DBNull] -or $val -eq '') { return 'NULL' }
    return Esc $val
}

# ── Helper: nullable uniqueidentifier ──
function GuidOrNull($val) {
    if ($null -eq $val -or $val -is [System.DBNull]) { return 'NULL' }
    return "'" + $val.ToString() + "'"
}

# ── Helper: nullable bit ──
function BitOrNull($val) {
    if ($null -eq $val -or $val -is [System.DBNull]) { return 'NULL' }
    if ($val) { return '1' } else { return '0' }
}

Write-Host "Querying widget tables..." -ForegroundColor Cyan

# ── Read all 4 tables ──
$categories = Invoke-Sql "SELECT CategoryId, Name, Workspace, Icon, DefaultOrder FROM widgets.WidgetCategory ORDER BY CategoryId"
$widgets    = Invoke-Sql "SELECT WidgetId, Name, WidgetType, ComponentKey, CategoryId, Description, DefaultConfig FROM widgets.Widget ORDER BY WidgetId"
$defaults   = Invoke-Sql "SELECT WidgetDefaultId, JobTypeId, RoleId, WidgetId, CategoryId, DisplayOrder, Config FROM widgets.WidgetDefault ORDER BY WidgetDefaultId"
$jobWidgets = Invoke-Sql "SELECT JobWidgetId, JobId, WidgetId, RoleId, CategoryId, DisplayOrder, IsEnabled, Config FROM widgets.JobWidget ORDER BY JobWidgetId"

Write-Host "  Categories: $($categories.Rows.Count)" -ForegroundColor Gray
Write-Host "  Widgets:    $($widgets.Rows.Count)" -ForegroundColor Gray
Write-Host "  Defaults:   $($defaults.Rows.Count)" -ForegroundColor Gray
Write-Host "  JobWidgets: $($jobWidgets.Rows.Count)" -ForegroundColor Gray

# ── Build output SQL ──
$sb = [System.Text.StringBuilder]::new()

$sb.AppendLine("-- ============================================================================") | Out-Null
$sb.AppendLine("-- Widget Configuration — Exported from Dev") | Out-Null
$sb.AppendLine("-- Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')") | Out-Null
$sb.AppendLine("--") | Out-Null
$sb.AppendLine("-- This script was auto-generated by Export-WidgetConfig.ps1") | Out-Null
$sb.AppendLine("-- It creates the widget schema (if needed) and loads dev's widget config.") | Out-Null
$sb.AppendLine("-- Fully idempotent. Safe to run repeatedly.") | Out-Null
$sb.AppendLine("--") | Out-Null
$sb.AppendLine("-- Prerequisites: reference.JobTypes + dbo.AspNetRoles populated") | Out-Null
$sb.AppendLine("-- ============================================================================") | Out-Null
$sb.AppendLine("") | Out-Null
$sb.AppendLine("SET NOCOUNT ON;") | Out-Null
$sb.AppendLine("") | Out-Null

# ════════════════════════════════════════
# BATCH 1: SCHEMA DDL (copied from seed)
# ════════════════════════════════════════
$sb.AppendLine("-- ════════════════════════════════════════════════════════════") | Out-Null
$sb.AppendLine("-- BATCH 1: SCHEMA + TABLES") | Out-Null
$sb.AppendLine("-- ════════════════════════════════════════════════════════════") | Out-Null
$sb.AppendLine("") | Out-Null

$sb.AppendLine("IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'widgets')") | Out-Null
$sb.AppendLine("    EXEC('CREATE SCHEMA [widgets] AUTHORIZATION [dbo]');") | Out-Null
$sb.AppendLine("") | Out-Null

# WidgetCategory
$sb.AppendLine("IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = 'widgets' AND t.name = 'WidgetCategory')") | Out-Null
$sb.AppendLine("BEGIN") | Out-Null
$sb.AppendLine("    CREATE TABLE [widgets].[WidgetCategory] (") | Out-Null
$sb.AppendLine("        [CategoryId]   INT IDENTITY(1,1) NOT NULL,") | Out-Null
$sb.AppendLine("        [Name]         NVARCHAR(100)     NOT NULL,") | Out-Null
$sb.AppendLine("        [Workspace]    NVARCHAR(20)      NOT NULL,") | Out-Null
$sb.AppendLine("        [Icon]         NVARCHAR(50)      NULL,") | Out-Null
$sb.AppendLine("        [DefaultOrder] INT               NOT NULL DEFAULT 0,") | Out-Null
$sb.AppendLine("        CONSTRAINT [PK_widgets_WidgetCategory] PRIMARY KEY CLUSTERED ([CategoryId])") | Out-Null
$sb.AppendLine("    );") | Out-Null
$sb.AppendLine("END") | Out-Null
$sb.AppendLine("") | Out-Null

# Widget
$sb.AppendLine("IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = 'widgets' AND t.name = 'Widget')") | Out-Null
$sb.AppendLine("BEGIN") | Out-Null
$sb.AppendLine("    CREATE TABLE [widgets].[Widget] (") | Out-Null
$sb.AppendLine("        [WidgetId]      INT IDENTITY(1,1) NOT NULL,") | Out-Null
$sb.AppendLine("        [Name]          NVARCHAR(100)     NOT NULL,") | Out-Null
$sb.AppendLine("        [WidgetType]    NVARCHAR(30)      NOT NULL,") | Out-Null
$sb.AppendLine("        [ComponentKey]  NVARCHAR(100)     NOT NULL,") | Out-Null
$sb.AppendLine("        [CategoryId]    INT               NOT NULL,") | Out-Null
$sb.AppendLine("        [Description]   NVARCHAR(500)     NULL,") | Out-Null
$sb.AppendLine("        [DefaultConfig] NVARCHAR(MAX)     NULL,") | Out-Null
$sb.AppendLine("        CONSTRAINT [PK_widgets_Widget] PRIMARY KEY CLUSTERED ([WidgetId]),") | Out-Null
$sb.AppendLine("        CONSTRAINT [FK_widgets_Widget_CategoryId] FOREIGN KEY ([CategoryId]) REFERENCES [widgets].[WidgetCategory] ([CategoryId]),") | Out-Null
$sb.AppendLine("        CONSTRAINT [CK_widgets_Widget_WidgetType] CHECK ([WidgetType] IN ('content','chart-tile','status-tile','link-tile'))") | Out-Null
$sb.AppendLine("    );") | Out-Null
$sb.AppendLine("END") | Out-Null
$sb.AppendLine("") | Out-Null

# WidgetDefault
$sb.AppendLine("IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = 'widgets' AND t.name = 'WidgetDefault')") | Out-Null
$sb.AppendLine("BEGIN") | Out-Null
$sb.AppendLine("    CREATE TABLE [widgets].[WidgetDefault] (") | Out-Null
$sb.AppendLine("        [WidgetDefaultId] INT IDENTITY(1,1) NOT NULL,") | Out-Null
$sb.AppendLine("        [JobTypeId]       INT               NOT NULL,") | Out-Null
$sb.AppendLine("        [RoleId]          NVARCHAR(450)     NOT NULL,") | Out-Null
$sb.AppendLine("        [WidgetId]        INT               NOT NULL,") | Out-Null
$sb.AppendLine("        [CategoryId]      INT               NOT NULL,") | Out-Null
$sb.AppendLine("        [DisplayOrder]    INT               NOT NULL DEFAULT 0,") | Out-Null
$sb.AppendLine("        [Config]          NVARCHAR(MAX)     NULL,") | Out-Null
$sb.AppendLine("        CONSTRAINT [PK_widgets_WidgetDefault] PRIMARY KEY CLUSTERED ([WidgetDefaultId]),") | Out-Null
$sb.AppendLine("        CONSTRAINT [FK_widgets_WidgetDefault_JobTypeId] FOREIGN KEY ([JobTypeId]) REFERENCES [reference].[JobTypes] ([JobTypeId]),") | Out-Null
$sb.AppendLine("        CONSTRAINT [FK_widgets_WidgetDefault_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[AspNetRoles] ([Id]),") | Out-Null
$sb.AppendLine("        CONSTRAINT [FK_widgets_WidgetDefault_WidgetId] FOREIGN KEY ([WidgetId]) REFERENCES [widgets].[Widget] ([WidgetId]),") | Out-Null
$sb.AppendLine("        CONSTRAINT [FK_widgets_WidgetDefault_CategoryId] FOREIGN KEY ([CategoryId]) REFERENCES [widgets].[WidgetCategory] ([CategoryId]),") | Out-Null
$sb.AppendLine("        CONSTRAINT [UQ_widgets_WidgetDefault_JobType_Role_Widget_Category] UNIQUE ([JobTypeId], [RoleId], [WidgetId], [CategoryId])") | Out-Null
$sb.AppendLine("    );") | Out-Null
$sb.AppendLine("END") | Out-Null
$sb.AppendLine("") | Out-Null

# JobWidget
$sb.AppendLine("IF NOT EXISTS (SELECT 1 FROM sys.tables t JOIN sys.schemas s ON t.schema_id = s.schema_id WHERE s.name = 'widgets' AND t.name = 'JobWidget')") | Out-Null
$sb.AppendLine("BEGIN") | Out-Null
$sb.AppendLine("    CREATE TABLE [widgets].[JobWidget] (") | Out-Null
$sb.AppendLine("        [JobWidgetId]  INT IDENTITY(1,1)    NOT NULL,") | Out-Null
$sb.AppendLine("        [JobId]        UNIQUEIDENTIFIER     NOT NULL,") | Out-Null
$sb.AppendLine("        [WidgetId]     INT                  NOT NULL,") | Out-Null
$sb.AppendLine("        [RoleId]       NVARCHAR(450)        NOT NULL,") | Out-Null
$sb.AppendLine("        [CategoryId]   INT                  NOT NULL,") | Out-Null
$sb.AppendLine("        [DisplayOrder] INT                  NOT NULL DEFAULT 0,") | Out-Null
$sb.AppendLine("        [IsEnabled]    BIT                  NOT NULL DEFAULT 1,") | Out-Null
$sb.AppendLine("        [Config]       NVARCHAR(MAX)        NULL,") | Out-Null
$sb.AppendLine("        CONSTRAINT [PK_widgets_JobWidget] PRIMARY KEY CLUSTERED ([JobWidgetId]),") | Out-Null
$sb.AppendLine("        CONSTRAINT [FK_widgets_JobWidget_JobId] FOREIGN KEY ([JobId]) REFERENCES [Jobs].[Jobs] ([JobId]),") | Out-Null
$sb.AppendLine("        CONSTRAINT [FK_widgets_JobWidget_WidgetId] FOREIGN KEY ([WidgetId]) REFERENCES [widgets].[Widget] ([WidgetId]),") | Out-Null
$sb.AppendLine("        CONSTRAINT [FK_widgets_JobWidget_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[AspNetRoles] ([Id]),") | Out-Null
$sb.AppendLine("        CONSTRAINT [FK_widgets_JobWidget_CategoryId] FOREIGN KEY ([CategoryId]) REFERENCES [widgets].[WidgetCategory] ([CategoryId]),") | Out-Null
$sb.AppendLine("        CONSTRAINT [UQ_widgets_JobWidget_Job_Widget_Role] UNIQUE ([JobId], [WidgetId], [RoleId])") | Out-Null
$sb.AppendLine("    );") | Out-Null
$sb.AppendLine("END") | Out-Null
$sb.AppendLine("") | Out-Null

# Schema migration (Section -> Workspace)
$sb.AppendLine("-- Schema migration: Section -> Workspace (prod backup compatibility)") | Out-Null
$sb.AppendLine("IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CK_widgets_WidgetCategory_Section')") | Out-Null
$sb.AppendLine("    ALTER TABLE [widgets].[WidgetCategory] DROP CONSTRAINT [CK_widgets_WidgetCategory_Section];") | Out-Null
$sb.AppendLine("IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CK_widgets_WidgetCategory_Workspace')") | Out-Null
$sb.AppendLine("    ALTER TABLE [widgets].[WidgetCategory] DROP CONSTRAINT [CK_widgets_WidgetCategory_Workspace];") | Out-Null
$sb.AppendLine("IF COL_LENGTH('widgets.WidgetCategory', 'Section') IS NOT NULL AND COL_LENGTH('widgets.WidgetCategory', 'Workspace') IS NULL") | Out-Null
$sb.AppendLine("    EXEC sp_rename 'widgets.WidgetCategory.Section', 'Workspace', 'COLUMN';") | Out-Null
$sb.AppendLine("") | Out-Null

# Constraint refresh
$sb.AppendLine("-- Refresh constraints") | Out-Null
$sb.AppendLine("IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UQ_widgets_WidgetDefault_JobType_Role_Widget' AND object_id = OBJECT_ID('widgets.WidgetDefault'))") | Out-Null
$sb.AppendLine("    ALTER TABLE [widgets].[WidgetDefault] DROP CONSTRAINT [UQ_widgets_WidgetDefault_JobType_Role_Widget];") | Out-Null
$sb.AppendLine("IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UQ_widgets_WidgetDefault_JobType_Role_Widget_Category' AND object_id = OBJECT_ID('widgets.WidgetDefault'))") | Out-Null
$sb.AppendLine("    ALTER TABLE [widgets].[WidgetDefault] ADD CONSTRAINT [UQ_widgets_WidgetDefault_JobType_Role_Widget_Category] UNIQUE ([JobTypeId], [RoleId], [WidgetId], [CategoryId]);") | Out-Null
$sb.AppendLine("") | Out-Null
$sb.AppendLine("IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CK_widgets_Widget_WidgetType')") | Out-Null
$sb.AppendLine("    ALTER TABLE [widgets].[Widget] DROP CONSTRAINT [CK_widgets_Widget_WidgetType];") | Out-Null
$sb.AppendLine("ALTER TABLE [widgets].[Widget] ADD CONSTRAINT [CK_widgets_Widget_WidgetType]") | Out-Null
$sb.AppendLine("    CHECK ([WidgetType] IN ('content','chart-tile','status-tile','link-tile'));") | Out-Null
$sb.AppendLine("") | Out-Null
$sb.AppendLine("PRINT 'Batch 1 complete: schema + tables + migration';") | Out-Null
$sb.AppendLine("GO") | Out-Null
$sb.AppendLine("") | Out-Null

# ════════════════════════════════════════
# BATCH 2: DATA (from dev)
# ════════════════════════════════════════
$sb.AppendLine("-- ════════════════════════════════════════════════════════════") | Out-Null
$sb.AppendLine("-- BATCH 2: DATA (exported from dev)") | Out-Null
$sb.AppendLine("-- ════════════════════════════════════════════════════════════") | Out-Null
$sb.AppendLine("") | Out-Null

# Workspace CHECK (temporarily open for data load)
$sb.AppendLine("-- Ensure Workspace CHECK is open for data load") | Out-Null
$sb.AppendLine("IF NOT EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CK_widgets_WidgetCategory_Workspace')") | Out-Null
$sb.AppendLine("BEGIN") | Out-Null
$workspaces = ($categories.Rows | ForEach-Object { "'" + $_.Workspace + "'" } | Sort-Object -Unique) -join ','
$sb.AppendLine("    ALTER TABLE [widgets].[WidgetCategory] ADD CONSTRAINT [CK_widgets_WidgetCategory_Workspace]") | Out-Null
$sb.AppendLine("        CHECK ([Workspace] IN ($workspaces));") | Out-Null
$sb.AppendLine("END") | Out-Null
$sb.AppendLine("") | Out-Null

# ── 2a. WidgetCategory: clear + reseed ──
$sb.AppendLine("-- ── WidgetCategory: clear and reseed ──") | Out-Null
$sb.AppendLine("-- (Safe: FK cascade not needed — we clear children first)") | Out-Null
$sb.AppendLine("DELETE FROM widgets.JobWidget;") | Out-Null
$sb.AppendLine("DELETE FROM widgets.WidgetDefault;") | Out-Null
$sb.AppendLine("DELETE FROM widgets.Widget;") | Out-Null
$sb.AppendLine("DELETE FROM widgets.WidgetCategory;") | Out-Null
$sb.AppendLine("") | Out-Null

$sb.AppendLine("SET IDENTITY_INSERT widgets.WidgetCategory ON;") | Out-Null
foreach ($row in $categories.Rows) {
    $sb.AppendLine("INSERT INTO widgets.WidgetCategory (CategoryId, Name, Workspace, Icon, DefaultOrder)") | Out-Null
    $sb.AppendLine("VALUES ($($row.CategoryId), $(Esc $row.Name), $(Esc $row.Workspace), $(StrOrNull $row.Icon), $($row.DefaultOrder));") | Out-Null
}
$sb.AppendLine("SET IDENTITY_INSERT widgets.WidgetCategory OFF;") | Out-Null
$sb.AppendLine("PRINT 'Loaded $($categories.Rows.Count) categories';") | Out-Null
$sb.AppendLine("") | Out-Null

# ── 2b. Widget ──
$sb.AppendLine("SET IDENTITY_INSERT widgets.Widget ON;") | Out-Null
foreach ($row in $widgets.Rows) {
    $sb.AppendLine("INSERT INTO widgets.Widget (WidgetId, Name, WidgetType, ComponentKey, CategoryId, Description, DefaultConfig)") | Out-Null
    $sb.AppendLine("VALUES ($($row.WidgetId), $(Esc $row.Name), $(Esc $row.WidgetType), $(Esc $row.ComponentKey), $($row.CategoryId), $(StrOrNull $row.Description), $(StrOrNull $row.DefaultConfig));") | Out-Null
}
$sb.AppendLine("SET IDENTITY_INSERT widgets.Widget OFF;") | Out-Null
$sb.AppendLine("PRINT 'Loaded $($widgets.Rows.Count) widgets';") | Out-Null
$sb.AppendLine("") | Out-Null

# ── 2c. WidgetDefault ──
$sb.AppendLine("SET IDENTITY_INSERT widgets.WidgetDefault ON;") | Out-Null
foreach ($row in $defaults.Rows) {
    $sb.AppendLine("INSERT INTO widgets.WidgetDefault (WidgetDefaultId, JobTypeId, RoleId, WidgetId, CategoryId, DisplayOrder, Config)") | Out-Null
    $sb.AppendLine("VALUES ($($row.WidgetDefaultId), $($row.JobTypeId), $(Esc $row.RoleId), $($row.WidgetId), $($row.CategoryId), $($row.DisplayOrder), $(StrOrNull $row.Config));") | Out-Null
}
$sb.AppendLine("SET IDENTITY_INSERT widgets.WidgetDefault OFF;") | Out-Null
$sb.AppendLine("PRINT 'Loaded $($defaults.Rows.Count) defaults';") | Out-Null
$sb.AppendLine("") | Out-Null

# ── 2d. JobWidget (may be empty) ──
if ($jobWidgets.Rows.Count -gt 0) {
    $sb.AppendLine("SET IDENTITY_INSERT widgets.JobWidget ON;") | Out-Null
    foreach ($row in $jobWidgets.Rows) {
        $sb.AppendLine("INSERT INTO widgets.JobWidget (JobWidgetId, JobId, WidgetId, RoleId, CategoryId, DisplayOrder, IsEnabled, Config)") | Out-Null
        $sb.AppendLine("VALUES ($($row.JobWidgetId), $(GuidOrNull $row.JobId), $($row.WidgetId), $(Esc $row.RoleId), $($row.CategoryId), $($row.DisplayOrder), $(BitOrNull $row.IsEnabled), $(StrOrNull $row.Config));") | Out-Null
    }
    $sb.AppendLine("SET IDENTITY_INSERT widgets.JobWidget OFF;") | Out-Null
}
$sb.AppendLine("PRINT 'Loaded $($jobWidgets.Rows.Count) job overrides';") | Out-Null
$sb.AppendLine("") | Out-Null

# ── Summary ──
$sb.AppendLine("-- ── Verification ──") | Out-Null
$sb.AppendLine("SELECT 'Categories' AS [Table], COUNT(*) AS [Count] FROM widgets.WidgetCategory") | Out-Null
$sb.AppendLine("UNION ALL SELECT 'Widgets', COUNT(*) FROM widgets.Widget") | Out-Null
$sb.AppendLine("UNION ALL SELECT 'Defaults', COUNT(*) FROM widgets.WidgetDefault") | Out-Null
$sb.AppendLine("UNION ALL SELECT 'JobWidgets', COUNT(*) FROM widgets.JobWidget;") | Out-Null
$sb.AppendLine("") | Out-Null
$sb.AppendLine("SET NOCOUNT OFF;") | Out-Null

# ── Write file ──
$sb.ToString() | Out-File -FilePath $OutputPath -Encoding UTF8
Write-Host ""
Write-Host "Exported to: $OutputPath" -ForegroundColor Green
Write-Host "  Categories: $($categories.Rows.Count)" -ForegroundColor Gray
Write-Host "  Widgets:    $($widgets.Rows.Count)" -ForegroundColor Gray
Write-Host "  Defaults:   $($defaults.Rows.Count)" -ForegroundColor Gray
Write-Host "  JobWidgets: $($jobWidgets.Rows.Count)" -ForegroundColor Gray
Write-Host ""
Write-Host "Run the output SQL against your target database to deploy widget config." -ForegroundColor Yellow
