/**
 * Type 1 (Crystal Reports) catalogue — hard-coded.
 *
 * Each entry maps to an existing ReportingController [HttpGet("X")] route;
 * `endpointPath` is the exact route name. The component calls
 * ReportingService.downloadReport(endpointPath, queryParams?) to run.
 *
 * Auth is enforced server-side per-endpoint (AllowAnonymous / AdminOnly /
 * StoreAdmin / Superuser). Clicking a report the user can't access returns
 * 403 — the component surfaces that, doesn't pre-gate.
 *
 * visibilityRules.jobTypes is derived from legacy 2025-2027 menu usage
 * (Jobs.JobMenus + JobMenu_Items, Controller='Reporting') — each entry is
 * only offered on job types where it was historically used. Reports that
 * spanned all six JobTypes (e.g. Discounted Players) are left unfiltered.
 *
 * `category` drives reports-library grouping; values must come from
 * ReportCategory union in report-categories.ts.
 *
 * Sort order = descending by legacy usage (2025-2027 JobCount).
 */

import type { VisibilityRules } from './visibility-rules';
import type { ReportCategory } from './report-categories';

export interface Type1ReportEntry {
    id: string;
    title: string;
    description?: string;
    iconName?: string;
    endpointPath: string;
    visibilityRules?: VisibilityRules;
    category: ReportCategory;
    sortOrder: number;
}

// --- JobType allowlist presets (keeps rows readable and dedupes typos) ---
const JT = {
    Camp:      'Camp Registration',
    ClubSport: 'Club Sport Registration',
    League:    'League Scheduling',
    Sales:     'Sales Venue',
    Showcase:  'Showcase Registration',
    Tournament:'Tournament Scheduling',
} as const;

const PRE_LEAGUE_TOURNAMENT: VisibilityRules = { jobTypes: [JT.League, JT.Tournament] };
const PRE_CLUB_SHOWCASE:     VisibilityRules = { jobTypes: [JT.ClubSport, JT.Showcase] };
const PRE_CAMP_TRIO:         VisibilityRules = { jobTypes: [JT.Sales, JT.Camp, JT.Showcase] };
const PRE_CAMP_PAIR:         VisibilityRules = { jobTypes: [JT.Sales, JT.Camp] };
const PRE_SHOWCASE_ONLY:     VisibilityRules = { jobTypes: [JT.Showcase] };
const PRE_CLUB_ONLY:         VisibilityRules = { jobTypes: [JT.ClubSport] };

export const TYPE1_REPORT_CATALOG: readonly Type1ReportEntry[] = [
    { id: 't1-player-transactions',             title: 'Player Transactions (Excel)',                description: 'Per-player transaction history for the job',                iconName: 'receipt',                   endpointPath: 'Get_JobPlayer_Transactions',                       visibilityRules: { jobTypes: [JT.Camp, JT.ClubSport, JT.Showcase, JT.League, JT.Tournament] }, category: 'Financials',     sortOrder: 10 },
    { id: 't1-net-users',                       title: 'Net Users (pdf)',                            description: 'Network-level user count across the platform',              iconName: 'people',                    endpointPath: 'Get_NetUsers',                                     visibilityRules: { jobTypes: [JT.Camp, JT.ClubSport, JT.League, JT.Tournament] },              category: 'Administration', sortOrder: 20 },
    { id: 't1-player-data-steps-excel',         title: 'Player Data (STEPS Excel)',                  description: 'Player roster export in STEPS column layout',               iconName: 'person-lines-fill',         endpointPath: 'Get_JobPlayers_STEPS_Excel',                       visibilityRules: { jobTypes: [JT.Camp, JT.ClubSport, JT.Showcase, JT.League, JT.Tournament] }, category: 'Rosters',        sortOrder: 30 },
    { id: 't1-staff-data',                      title: 'Staff Data (Excel)',                         description: 'Staff roster export',                                       iconName: 'people-fill',               endpointPath: 'JobStaff_Excel',                                   visibilityRules: { jobTypes: [JT.ClubSport, JT.Showcase, JT.League, JT.Tournament] },          category: 'Rosters',        sortOrder: 40 },
    { id: 't1-field-utilization-tourn',         title: 'Field Utilization - Tournament (pdf)',       description: 'Tournament field-hour utilization summary',                 iconName: 'geo-alt',                   endpointPath: 'FieldUtilizationAcrossLeaguesTournament',          visibilityRules: PRE_LEAGUE_TOURNAMENT, category: 'Schedules',     sortOrder: 50 },
    { id: 't1-field-utilization-tourn-by-date', title: 'Field Utilization by Date (pdf)',            description: 'Tournament field utilization sliced by date',               iconName: 'calendar-date',             endpointPath: 'FieldUtilizationAcrossLeaguesByDateTournament',    visibilityRules: PRE_LEAGUE_TOURNAMENT, category: 'Schedules',     sortOrder: 60 },
    { id: 't1-schedule-by-agegroup',            title: 'Game Boards by Agegroup (pdf)',              description: 'Printable game boards grouped by agegroup',                 iconName: 'grid-3x3',                  endpointPath: 'Schedule_ByAgegroup',                              visibilityRules: { jobTypes: [JT.Showcase, JT.League, JT.Tournament] }, category: 'Schedules',     sortOrder: 70 },
    { id: 't1-tourny-checkin',                  title: 'Tournament Check-In (pdf)',                  description: 'Tournament team check-in sheets',                           iconName: 'clipboard-check',           endpointPath: 'TournyCheckin',                                    visibilityRules: PRE_LEAGUE_TOURNAMENT, category: 'Schedules',     sortOrder: 80 },
    { id: 't1-recruiting-report',               title: 'Recruiting Report (pdf)',                    description: 'Tournament recruiting summary for college coaches',         iconName: 'journal-bookmark',          endpointPath: 'TournamentRecruitingReport',                       visibilityRules: PRE_LEAGUE_TOURNAMENT, category: 'Recruiting',    sortOrder: 90 },
    { id: 't1-recruiting-dump',                 title: 'Recruiting Data Dump (Excel)',               description: 'Full data export of recruiting report',                     iconName: 'file-earmark-spreadsheet',  endpointPath: 'TournamentRecruitingReport_DataDump',              visibilityRules: PRE_LEAGUE_TOURNAMENT, category: 'Recruiting',    sortOrder: 100 },
    { id: 't1-rosters-packed-noclub',           title: 'Rosters Packed - No Club Players (pdf)',     description: 'Packed rosters by position, excluding club players',        iconName: 'layers',                    endpointPath: 'Get_JobRosters_PackedByPositionAGNoClubPlayers',   visibilityRules: PRE_CLUB_SHOWCASE, category: 'Rosters',           sortOrder: 110 },
    { id: 't1-rosters-recruiting-excel',        title: 'Recruiting Rosters Data Dump (Excel)',       description: 'Recruiting-report rosters in dumpable Excel',               iconName: 'file-earmark-excel',        endpointPath: 'Get_JobRosters_RecruitingReport_DumpExcel',        visibilityRules: PRE_CLUB_SHOWCASE, category: 'Recruiting',        sortOrder: 120 },
    { id: 't1-rosters-recruiting-public',       title: 'Recruiting Rosters (Public, Excel)',         description: 'Public-facing recruiting roster dump',                      iconName: 'share',                     endpointPath: 'Get_JobRosters_RecruitingReport_Public_DumpExcel', visibilityRules: PRE_CLUB_SHOWCASE, category: 'Recruiting',        sortOrder: 130 },
    { id: 't1-rosters-recruiting-pdf',          title: 'Recruiting Rosters Report (pdf)',            description: 'Formatted recruiting roster PDF',                           iconName: 'file-earmark-pdf',          endpointPath: 'Get_JobRosters_RecruitingReport',                  visibilityRules: PRE_CLUB_SHOWCASE, category: 'Recruiting',        sortOrder: 140 },
    { id: 't1-player-details-yj',               title: 'Player Details (YJ Excel)',                  description: 'Full player detail export (YJ format)',                     iconName: 'person-vcard',              endpointPath: 'JobPlayers_YJ_Excel',                              visibilityRules: { jobTypes: [JT.Sales, JT.Camp, JT.ClubSport, JT.Showcase, JT.Tournament] }, category: 'Rosters',         sortOrder: 150 },
    { id: 't1-tournament-rosters-school',       title: 'Tournament Rosters Packed - by School (pdf)', description: 'Packed tournament rosters grouped by school',              iconName: 'mortarboard',               endpointPath: 'TournamentRosterPacked_PositionSchool',            visibilityRules: PRE_LEAGUE_TOURNAMENT, category: 'Rosters',       sortOrder: 160 },
    { id: 't1-american-select-checkin',         title: 'American Select Check-In (pdf)',             description: 'Tournament check-in for American Select',                   iconName: 'clipboard2-check',          endpointPath: 'AmericanSelectTournyCheckin',                      visibilityRules: PRE_CLUB_SHOWCASE, category: 'Schedules',         sortOrder: 170 },
    { id: 't1-american-select-eval',            title: 'American Select Evaluation (pdf)',           description: 'Player evaluation sheet for American Select',               iconName: 'clipboard-data',            endpointPath: 'AmericanSelectEvaluation',                         visibilityRules: PRE_SHOWCASE_ONLY, category: 'Rosters',           sortOrder: 180 },
    { id: 't1-american-select-main-event',      title: 'American Select Main Event Rosters (pdf)',   description: 'Main event roster sheets for American Select',              iconName: 'trophy',                    endpointPath: 'AmericanSelectMainEventRosters',                   visibilityRules: PRE_SHOWCASE_ONLY, category: 'Rosters',           sortOrder: 190 },
    { id: 't1-club-rosters-nomedical',          title: 'Club Rosters - No Medical (pdf)',            description: 'Club roster pack without medical columns',                  iconName: 'shield',                    endpointPath: 'Job_Rosters_NoMedical',                            visibilityRules: { jobTypes: [JT.Camp, JT.ClubSport] }, category: 'Rosters',                   sortOrder: 200 },
    { id: 't1-discounted-players',              title: 'Discounted Players (Excel)',                 description: 'Players holding a discount code',                           iconName: 'tags',                      endpointPath: 'Get_DiscountedPlayers',                            category: 'Financials',                                                                       sortOrder: 210 },
    { id: 't1-player-data-all-jobs',            title: 'Player Data - All Customer Jobs (Excel)',    description: 'Cross-job player roster for a customer',                    iconName: 'building',                  endpointPath: 'Get_CustomerPlayers1',                             visibilityRules: { jobTypes: [JT.Camp, JT.ClubSport, JT.Showcase] }, category: 'Rosters',      sortOrder: 220 },
    { id: 't1-tournament-rosters-packed',       title: 'Tournament Rosters Packed (pdf)',            description: 'Standard packed tournament roster sheets',                  iconName: 'list-ul',                   endpointPath: 'TournamentRosterPacked',                           visibilityRules: PRE_LEAGUE_TOURNAMENT, category: 'Rosters',       sortOrder: 230 },
    { id: 't1-playerstats-e120',                title: 'Player Stats E120 Entry Form (pdf)',         description: 'E120 stats entry form',                                     iconName: 'pencil-square',             endpointPath: 'PlayerStats_E120',                                 visibilityRules: PRE_CLUB_SHOWCASE, category: 'Rosters',           sortOrder: 240 },
    { id: 't1-player-data-e120-excel',          title: 'Player Data (E120 Excel)',                   description: 'Player roster in E120 column layout',                       iconName: 'person-lines-fill',         endpointPath: 'Get_JobPlayers_E120_Excel',                        visibilityRules: PRE_CLUB_SHOWCASE, category: 'Rosters',           sortOrder: 250 },
    { id: 't1-active-players-steps-pdf',        title: 'Active Players Report (STEPS pdf)',          description: 'Active-players summary in STEPS layout',                    iconName: 'person-check',              endpointPath: 'Get_JobPlayers_STEPS',                             visibilityRules: { jobTypes: [JT.Camp, JT.ClubSport, JT.League] }, category: 'Rosters',        sortOrder: 260 },
    { id: 't1-club-rosters',                    title: 'Club Rosters (pdf)',                         description: 'Standard club roster pack',                                 iconName: 'people',                    endpointPath: 'Job_Club_Rosters',                                 visibilityRules: { jobTypes: [JT.Camp, JT.ClubSport, JT.Tournament] }, category: 'Rosters',    sortOrder: 270 },
    { id: 't1-camp-checkin',                    title: 'Camp Check-In (pdf)',                        description: 'Camp arrival check-in sheets',                              iconName: 'clipboard2',                endpointPath: 'Job_CampCheckin',                                  visibilityRules: PRE_CAMP_TRIO, category: 'Camp',                  sortOrder: 280 },
    { id: 't1-camp-datadump',                   title: 'Camp Data Dump (Excel)',                     description: 'Raw camp export - all columns',                             iconName: 'database',                  endpointPath: 'camp_datadump',                                    visibilityRules: PRE_CAMP_TRIO, category: 'Camp',                  sortOrder: 290 },
    { id: 't1-camp-export-long',                title: 'Camp Export - Long (Excel)',                 description: 'Long-form camp export',                                     iconName: 'file-earmark-excel',        endpointPath: 'camp_excelexport_long',                            visibilityRules: PRE_CAMP_TRIO, category: 'Camp',                  sortOrder: 300 },
    { id: 't1-camp-export-short',               title: 'Camp Export - Short (Excel)',                description: 'Short-form camp export',                                    iconName: 'file-earmark-excel',        endpointPath: 'camp_excelexport_short',                           visibilityRules: PRE_CAMP_TRIO, category: 'Camp',                  sortOrder: 310 },
    { id: 't1-camp-export-veryshort',           title: 'Camp Export - Very Short (Excel)',           description: 'Minimal camper export',                                     iconName: 'file-earmark-excel',        endpointPath: 'camp_excelexport_veryshort',                       visibilityRules: PRE_CAMP_TRIO, category: 'Camp',                  sortOrder: 320 },
    { id: 't1-club-rosters-coaches-ii',         title: 'Club Rosters for Coaches (pdf)',             description: 'Coach-facing club roster pack',                             iconName: 'clipboard-heart',           endpointPath: 'clubrostersNoMedicalII',                           visibilityRules: { jobTypes: [JT.Camp, JT.ClubSport, JT.Tournament] }, category: 'Rosters',    sortOrder: 330 },
    { id: 't1-camp-commuters',                  title: 'Camp Commuters (pdf)',                       description: 'Day commuter roster',                                       iconName: 'house',                     endpointPath: 'camp_commuters',                                   visibilityRules: PRE_CAMP_PAIR, category: 'Camp',                  sortOrder: 340 },
    { id: 't1-camp-daygroups-excel',            title: 'Camp Day/Night Groups (Excel)',              description: 'Camp daygroup + nightgroup rosters',                        iconName: 'file-earmark-excel',        endpointPath: 'camp_excelexport_daygroups',                       visibilityRules: PRE_CAMP_PAIR, category: 'Camp',                  sortOrder: 350 },
    { id: 't1-camp-daygroups-pdf',              title: 'Camp Daygroups (pdf)',                       description: 'Daygroup rosters',                                          iconName: 'sun',                       endpointPath: 'camp_daygroups',                                   visibilityRules: PRE_CAMP_TRIO, category: 'Camp',                  sortOrder: 360 },
    { id: 't1-camp-daygroups-stacked',          title: 'Camp Daygroups - Stacked (pdf)',             description: 'Stacked-layout daygroup sheets',                            iconName: 'stack',                     endpointPath: 'camp_daygroups_pdf',                               visibilityRules: PRE_CAMP_PAIR, category: 'Camp',                  sortOrder: 370 },
    { id: 't1-camp-nightgroups-pdf',            title: 'Camp Nightgroups (pdf)',                     description: 'Nightgroup rosters',                                        iconName: 'moon',                      endpointPath: 'camp_nightgroups',                                 visibilityRules: PRE_CAMP_PAIR, category: 'Camp',                  sortOrder: 380 },
    { id: 't1-camp-nightgroups-stacked',        title: 'Camp Nightgroups - Stacked (pdf)',           description: 'Stacked-layout nightgroup sheets',                          iconName: 'stack',                     endpointPath: 'camp_nightgroups_pdf',                             visibilityRules: PRE_CAMP_PAIR, category: 'Camp',                  sortOrder: 390 },
    { id: 't1-camp-roomies-excel',              title: 'Camp Roommates (Excel)',                     description: 'Roommate list export',                                      iconName: 'file-earmark-excel',        endpointPath: 'camp_excelexport_roomies',                         visibilityRules: PRE_CAMP_PAIR, category: 'Camp',                  sortOrder: 400 },
    { id: 't1-camp-roomies-pdf',                title: 'Camp Roommates (pdf)',                       description: 'Printable roommate list',                                   iconName: 'house-heart',               endpointPath: 'camp_roomies',                                     visibilityRules: PRE_CAMP_PAIR, category: 'Camp',                  sortOrder: 410 },
    { id: 't1-camp-roomies-position',           title: 'Camp Roommates with Position (Excel)',       description: 'Roommate list including playing position',                  iconName: 'diagram-3',                 endpointPath: 'camp_excelexport_room_position',                   visibilityRules: PRE_CAMP_PAIR, category: 'Camp',                  sortOrder: 420 },
    { id: 't1-playerstats-parisi-excel',        title: 'Player Stats Export - Parisi (Excel)',       description: 'Parisi lab stats export',                                   iconName: 'speedometer2',              endpointPath: 'PlayerStats_ParisiExportExcel',                    visibilityRules: PRE_SHOWCASE_ONLY, category: 'Rosters',           sortOrder: 430 },
    { id: 't1-rosters-packed-xpo',              title: 'Rosters Packed XPO (pdf)',                   description: 'XPO-format packed rosters',                                 iconName: 'layers',                    endpointPath: 'Get_JobRosters_PackedByPosition_XPO',              visibilityRules: PRE_SHOWCASE_ONLY, category: 'Rosters',           sortOrder: 440 },
    { id: 't1-rosters-recruiting-xpo',          title: 'Recruiting Rosters XPO (pdf)',               description: 'XPO-format recruiting rosters',                             iconName: 'journal-bookmark',          endpointPath: 'Get_JobRosters_RecruitingReport_XPO',              visibilityRules: PRE_SHOWCASE_ONLY, category: 'Recruiting',        sortOrder: 450 },
    { id: 't1-team-field-distribution',         title: 'Team Field Distribution',                    description: 'Distribution of teams across fields',                       iconName: 'diagram-2',                 endpointPath: 'Get_TeamFieldDistribution',                        visibilityRules: PRE_LEAGUE_TOURNAMENT, category: 'Schedules',     sortOrder: 460 },
    { id: 't1-mobile-users',                    title: 'Mobile Users (Excel)',                       description: 'Mobile app user list for the job',                          iconName: 'phone',                     endpointPath: 'Mobile_JobUsers',                                  visibilityRules: PRE_CLUB_ONLY, category: 'Administration',        sortOrder: 470 },
    { id: 't1-tryouts-check',                   title: 'Tryouts Check-In Report (pdf)',              description: 'Player check-in sheet for tryouts',                         iconName: 'clipboard-check',           endpointPath: 'JobRosters_TryoutsCheckReport',                    visibilityRules: PRE_CLUB_ONLY, category: 'Registrations',         sortOrder: 480 },
    { id: 't1-daygroups-packed-xpo',            title: 'Daygroups Packed XPO (pdf)',                 description: 'XPO-format daygroup packed sheets',                         iconName: 'stack',                     endpointPath: 'JobRosters_DayGroupsPackedXPO',                    visibilityRules: PRE_SHOWCASE_ONLY, category: 'Camp',              sortOrder: 490 },
    { id: 't1-isp-checkin-flat',                title: 'ISP Check-In (Flat)',                        description: 'Flat ISP check-in layout',                                  iconName: 'clipboard',                 endpointPath: 'ISP_CheckinFlat',                                  visibilityRules: { jobTypes: [JT.ClubSport, JT.League] }, category: 'Schedules',                sortOrder: 500 },
    { id: 't1-player-data-liberty-excel',       title: 'Player Data - Liberty (Excel)',              description: 'Player roster in Liberty column layout',                    iconName: 'person-lines-fill',         endpointPath: 'Get_JobPlayers_Liberty_Excel',                     visibilityRules: PRE_CLUB_ONLY, category: 'Rosters',               sortOrder: 510 },
    { id: 't1-score-input',                     title: 'Score Entry Sheets',                         description: 'Blank score-entry sheets for officials',                    iconName: 'pencil-square',             endpointPath: 'Score_Input',                                      visibilityRules: { jobTypes: [JT.ClubSport, JT.League] }, category: 'Schedules',                sortOrder: 520 },

    // ── SuperUser cross-customer reports (TSIC home / monthly close) ──────
    // Run from TSIC home job; intentionally not job-type-gated since they cover ALL jobs.
    // Daily Reg Counts is BE-anonymous but legacy menu placed it under SuperUser — gate
    // here to match. The Crystal accounting items are AdminOnly server-side, but legacy
    // showed them only to SuperUser.
    { id: 't1-su-daily-reg-counts',             title: 'Daily Registration Counts (PDF)',            description: 'TSIC daily registration count report',                      iconName: 'calendar-check',            endpointPath: 'Get_JobPlayers_TSICDAILY',                         visibilityRules: { requiresRoles: ['Superuser'] }, category: 'Administration', sortOrder: 1010 },
    { id: 't1-su-tsic-fees-ytd-customer',       title: 'TSIC Fees YTD by Customer',                  description: 'Year-to-date TSIC fees rolled up per customer',             iconName: 'graph-up',                  endpointPath: 'TSICFeesYTDByCustomer',                            visibilityRules: { requiresRoles: ['Superuser'] }, category: 'Financials',     sortOrder: 1020 },
    { id: 't1-su-tsic-fees-ytd-customer-job',   title: 'TSIC Fees YTD by Customer + Job',            description: 'Year-to-date TSIC fees broken out by customer and job',     iconName: 'graph-up-arrow',            endpointPath: 'TSICFeesYTDByCustomerAndJob',                      visibilityRules: { requiresRoles: ['Superuser'] }, category: 'Financials',     sortOrder: 1030 },
    { id: 't1-su-last-month-invoices',          title: 'Last Month Invoices (PDF)',                  description: 'Prior month customer invoices',                             iconName: 'file-earmark-pdf',          endpointPath: 'Get_Invoices_LastMonth',                           visibilityRules: { requiresRoles: ['Superuser'] }, category: 'Financials',     sortOrder: 1040 },
    { id: 't1-su-last-month-invoice-summaries', title: 'Last Month Invoice Summaries (PDF)',         description: 'Summaries-only view of prior month customer invoices',      iconName: 'file-earmark-text',         endpointPath: 'Get_Invoices_LastMonthSummariesOnly',              visibilityRules: { requiresRoles: ['Superuser'] }, category: 'Financials',     sortOrder: 1050 },
];
