name: CI

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '9.0.x' ]
        node: [ '20' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'

    - name: Restore & build backend
      working-directory: TSIC-Core-Angular
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore

    - name: Run backend tests
      working-directory: TSIC-Core-Angular
      run: dotnet test --no-build --verbosity minimal

    - name: Check dotnet format
      working-directory: TSIC-Core-Angular
      run: |
        dotnet tool restore
        dotnet format --verify-no-changes

    - name: Install frontend deps
      working-directory: TSIC-Core-Angular/src/frontend/tsic-app
      run: npm ci

    - name: Build frontend
      working-directory: TSIC-Core-Angular/src/frontend/tsic-app
      run: npm run build --if-present

    - name: Upload backend build artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: TSIC-Core-Angular/src/backend/TSIC.API/bin/Release/net9.0/
