name: Release on tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build (Release)
        run: dotnet build TSIC-Core-Angular.sln --configuration Release

      - name: Run tests
        run: dotnet test TSIC-Core-Angular.sln --no-build --configuration Release

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Release created by CI.
            Tag: ${{ github.ref_name }}
